"""
Django settings for safevoice project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'rest_framework.authtoken',
    'reports',
    'encrypted_model_fields',
    'adminpanel',
      'rest_framework_simplejwt.token_blacklist',
    
     ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'safevoice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'safevoice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DATABASE_ENGINE'),
        'NAME': config('DATABASE_NAME'),
        'USER': config('DATABASE_USER'),
        'PASSWORD': config('DATABASE_PASSWORD'),
        'HOST': config('DATABASE_HOST'),
        'PORT': config('DATABASE_PORT'),
    }
}

CLOUDINARY = {
    'cloud_name': config('CLOUDINARY_CLOUD_NAME'),
    'api_key': config('CLOUDINARY_API_KEY'),
    'api_secret': config('CLOUDINARY_API_SECRET'),
}

FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY')
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = config('MEDIA_URL', default='/media')
MEDIA_ROOT = BASE_DIR / config('MEDIA_ROOT', default='media')

Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "token_blacklist_outstandingtoken" does not exist
LINE 1: INSERT INTO "token_blacklist_outstandingtoken" ("user_id", "...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response        
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper      
    return view_func(request, *args, **kwargs)       
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)   
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^   
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception  
    raise exc
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)     
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)        
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^        
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation      
    value = self.validate(value)
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 75, in validate   
    refresh = self.get_token(self.user)
  File "C:\Users\best budget\software_dev\django-projects\safevoice\accounts\serializers.py", line 43, in 
get_token
    token = super().get_token(user)
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 66, in get_token  
    return cls.token_class.for_user(user)  # type: ignore
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\rest_framework_simplejwt\tokens.py", line 331, in for_user       
    OutstandingToken.objects.create(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        user=user,
        ^^^^^^^^^^
    ...<3 lines>...
        expires_at=datetime_from_epoch(exp),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, 
**kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)       
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, 
**kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\models\query.py", line 1864, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql     
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers 
    return executor(sql, params, many, context)      
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\best budget\software_dev\django-projects\safevoice\virtual\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "token_blacklist_outstandingtoken" does not exist
LINE 1: INSERT INTO "token_blacklist_outstandingtoken" ("user_id", "...
                    ^

[25/May/2025 20:10:44] "POST /api/login/ HTTP/1.1" 500 218254
